### ISSUE TITLE
Failed to use nerd font in bar

### ISSUE THREAD

**Issue by hongyuanjia** [glazerdesktop/GlazeWM#375]
I failed to use nerd font in the bar. I recalled that it worked some time ago. I did not know if the Nerd Font version updating caused this. ([from v2 to v3](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0)). Thanks for the help!

```yaml
bar:
  components_left:
    - type: "workspaces"
      font_family: "JetBrainsMono NF"
      font_size: "15px"
```
