### ISSUE TITLE
Focus Mouse WM

### ISSUE THREAD

**Issue by pex81** [glazerdesktop/GlazeWM#406]
Hi, congratulations on the very useful application.
On Windows 11 I'm finding that the focus by moving the mouse over the windows works, but by moving the keys the mouse doesn't move.

```
general:
  # Whether to show floating windows as always on top.
  show_floating_on_top: true
  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: true
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true
```

GlazeWM 2.0.1
