### ISSUE TITLE
Monitors appear swap

### ISSUE THREAD

**Issue by DarylGraves** [glazerdesktop/GlazeWM#407]
Just wanted to highlight a small bug.

In my config file I have this: 

```
workspaces:
  - name: "1"
    display_name: "Main (1)"
    bind_to_monitor: 1
  - name: "2"
    display_name: "Chat (2)"
    bind_to_monitor: 1
```

In Display Settings, the monitor labelled 2 is receiving "Main (1)" and my monitor labelled 1 is receiving window 6.

Thanks!

**Comment by ItsLolgical** [comment]
Just wanted to come here an echo that I have this same issue. Here is my config currently:

```
workspaces:
  - name: "1"
    bind_to_monitor: 3
    keep_alive: true
  - name: "2"
    bind_to_monitor: 3
    keep_alive: true
  - name: "3"
    bind_to_monitor: 3
    keep_alive: true
  - name: "4"
    bind_to_monitor: 2
    keep_alive: true
  - name: "5"
    bind_to_monitor: 2
    keep_alive: true
  - name: "6"
    bind_to_monitor: 2
    keep_alive: true
  - name: "7"
    bind_to_monitor: 1
    keep_alive: true
  - name: "8"
    bind_to_monitor: 1
    keep_alive: true
  - name: "9"
    bind_to_monitor: 1
    keep_alive: true
```

I have to have monitor 1 & 3 flipped because of the aforementioned bug.
