### ISSUE TITLE
Annoying border for workspace icon 

### ISSUE THREAD

**Issue by Lol-Lap** [glazerdesktop/GlazeWM#420]
Since I installed Glaze and I have this annoying border blue color, I have tried to edit the config and even opened a ticket on Discord, but we couldn't figure out where it's coming from.
![image](https://github.com/glazerdesktop/GlazeWM/assets/120711779/a3c7beee-8975-4ce2-a1da-5dcc434e8d4d)

**Comment by azinsharaf** [comment]
do you have this in `bar` section?
```
  border_width: "0"
  # Color of the border.
  border_color: "green"
```

**Comment by jwong00** [comment]
Having the same issue. The border around the workspace icon number is blue, and does NOT appear to be affected by the properties that would seem to be the correct ones:

```
components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
      border_width: "1"
      border_color: "white"
```

Notably, when I added the border_width: "1", I get a white border of pixel width 1... on top of the much thicker blue border.

**Comment by Lol-Lap** [comment]
> Having the same issue. The border around the workspace icon number is blue, and does NOT appear to be affected by the properties that would seem to be the correct ones:
> 
> ```
> components_left:
>     - type: "workspaces"
>       focused_workspace_background: "#ffffff33"
>       displayed_workspace_background: "#00000033"
>       default_workspace_background: "transparent"
>       border_width: "1"
>       border_color: "white"
> ```
> 
> Notably, when I added the border_width: "1", I get a white border of pixel width 1... on top of the much thicker blue border.

Well, turns out this problem related to windows themes "theming windows with Ultrauxthemepatcher or SecureUX" so uninstall the theme or just do this 
```yaml
components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
      
      focused_workspace_border_color: "transparent"
      displayed_workspace_border_color: "transparent"
      default_workspace_border_color: "transparent"
```
