### ISSUE TITLE
Mouse cursor doesn't follow focus 

### ISSUE THREAD

**Issue by Lol-Lap** [glazerdesktop/GlazeWM#423]
When shifting focus with the keybinds, the cursor doesn't follow the focus.

```yaml
general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: true

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: true
```
info:
on the last version 2.0.3 installed via Scoop
![image](https://github.com/glazerdesktop/GlazeWM/assets/120711779/d8e62515-1f77-4a12-ab40-fd4342a7d9b9)

but in the terminal, says
![image](https://github.com/glazerdesktop/GlazeWM/assets/120711779/812ba748-8019-4abe-b856-ae0f7306bfc9)
