### ISSUE TITLE
Unable to disambiguate between processes when configuring window_rules

### ISSUE THREAD

**Issue by kaerum** [glazerdesktop/GlazeWM#447]
First of all, let me thank the contributors for this amazing project. It is by far the best experience I have had with getting windows as close to my dream unix setup.

### Use case

I use profiles with Firefox, one for work and one not for work, such that I can keep different preferences/bookmarks/history/etc. I would like to be able to have them be moved to different workspaces such that NotWork goes to 1 and Work goes to 3.

Here is the relevant part of the config:

```yml
  - command: "move to workspace 1"
    match_process_name: "firefox"

  - command: "move to workspace 3"
    match_process_name: "firefox"

```

Problem is, I can't seem to be able to disambiguate between them, their process name is the same, class is the same ( I haven't actually checked this but from what I understand it should not be different ) and title depends on which page I am accessing.

### Proposed solution
These are the command line arguments for each process as described by task manager.
![image](https://github.com/glazerdesktop/GlazeWM/assets/109406743/67716541-e79b-41eb-8d39-7591d16c8a90)
![image](https://github.com/glazerdesktop/GlazeWM/assets/109406743/2e4486d3-f601-45d2-a359-f911c1daa5f7)

As can be seen, they have different command line values, so my proposal is to add a match_process_command matcher that, well, matches against the process's command line such that the following configuration would be valid:

```yml
  - command: "move to workspace 1"
    match_process_name: "firefox"
    match_process_command: "/-p NotWork/"

  - command: "move to workspace 3"
    match_process_name: "firefox"
    match_process_command: "/-p Work/"
```

### Implementation

I have looked into how one would implement this, and I have discovered a couple of things:
1. It seems there is no public API on dotnet that exposes a process's command line, we only have access to Process's [StartInfo](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=net-8.0) and that is only true when the Process has been started by us, otherwise we either error out or get a dummy value in return.
2. You can use [WMI](https://learn.microsoft.com/en-us/dotnet/api/system.management?view=dotnet-plat-ext-7.0) to get command line information, I have a sample implementation [here](https://github.com/kaerum/GlazeWM/commit/75d66d235761b78a70b1f476140ae68401dd8534) that seems to work fine for me but I have seen comments around suggesting that WMI could be slow. I have tested and on my computer it takes an average of 30ms for WMI to return the process's command line.
3. It seems you can use [NtQueryProcessInformation](https://learn.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntqueryinformationprocess) to get access to a [PEB](https://learn.microsoft.com/en-us/windows/win32/api/winternl/ns-winternl-peb) struct that contains the process's command line information within it. It is possible to implement it using [P/Invoke](https://github.com/dahall/Vanara/tree/master/PInvoke/NtDll) but it seems that this PEB struct is subject to change and has changed in the past ( meaning a different implementation for each supported windows version ). I have found a couple of implementations around but it seems to take considerably more effort than 2
   a. https://github.com/Vlas-Omsk/GetProcessCommandLine
   b. [https://github.com/winsiderss/systeminformer](https://github.com/winsiderss/systeminformer/blob/master/phlib/native.c#L1262)
